### ISSUE TITLE
Snippet 

### ISSUE THREAD

**Issue by CforED** [ClydeDz/google-analytics-snippet-pack#4]
ClydeDz,

What snippet should I deploy on to my host server to Track Email Campaign Clicks, Using Google Tag Manager?

Campaign URL Builder at https://ga-dev-tools.appspot.com/campaign-url-builder/

Regards,
Hal

**Comment by ClydeDz** [comment]
Hi Hal @CforED ,

These campaign URLs would be placed in external sources (email newsletters, for example) that will link back to your website. I don't have a snippet to generate these URLs. 

However, if you want to see the report of your campaign, then you should be able to see the results directly in Google Analytics, as mentioned in [this article](https://digitalbrandinginstitute.com/google-analytics-track-email-campaigns/), assuming you have the default script added to the `<head>` section of your website. 

This extension only supports the `gtag.js` approach, in which case, [this snippet](https://github.com/ClydeDz/google-analytics-snippet-pack/blob/master/GASnippetPack/GoogleAnalyticsSnippetPack/Snippets/HTML%20Google%20Analytics%20Snippet%20Pack/gtag/BasicInstall.snippet) should be enough. Unfortunately, I don't have a snippet for a Google Tag Manager implementation. I can refer you to [this article](https://support.google.com/tagmanager/answer/6103696?hl=en) though that might help you set up GTM.

Thanks, 
Clyde
